### ISSUE TITLE
Contract tests failure

### ISSUE THREAD

**Issue by gurrpi** [quadratic-funding/qfi#60]
### Test Summary
```
181 passing (32m)
  20 failing

  1) Grant Round
       publishTallyHash()
         revert - grant round finalized:

      AssertionError: Expected transaction to be reverted
      + expected - actual

      -Transaction NOT reverted.
      +Transaction reverted.



  2) Grant Round
       finalize()
         allow owner to finalize the grant round:
     TransactionExecutionError: VM Exception while processing transaction: revert with reason "GrantRound: Incorrect total amount of spent voice credits"
      at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1830:14)
      at HardhatNode.estimateGas (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:693:27)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  3) Grant Round
       finalize()
         revert - grant round already finalized:
     TransactionExecutionError: VM Exception while processing transaction: revert with reason "GrantRound: Incorrect total amount of spent voice credits"
      at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1830:14)
      at HardhatNode.estimateGas (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:693:27)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  4) Grant Round
       getAllocatedAmount()
         allow anyone to retrieve the allocated token amount (without verification):
     TransactionExecutionError: VM Exception while processing transaction: revert with reason "GrantRound: Incorrect total amount of spent voice credits"
      at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1830:14)
      at HardhatNode.estimateGas (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:693:27)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  5) Grant Round
       claimFunds()
         allow a recipient to claim the funds:
     TransactionExecutionError: VM Exception while processing transaction: revert with reason "GrantRound: Incorrect total amount of spent voice credits"
      at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1830:14)
      at HardhatNode.estimateGas (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:693:27)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  6) Grant Round
       claimFunds()
         allow to send funds back to the matching pool if recipient address is zero:
     TransactionExecutionError: VM Exception while processing transaction: revert with reason "GrantRound: Incorrect total amount of spent voice credits"
      at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1830:14)
      at HardhatNode.estimateGas (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:693:27)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  7) Grant Round
       claimFunds()
         revert - funds already claimed:
     TransactionExecutionError: VM Exception while processing transaction: revert with reason "GrantRound: Incorrect total amount of spent voice credits"
      at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1830:14)
      at HardhatNode.estimateGas (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:693:27)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  8) Grant Round
       claimFunds()
         revert - incorrect tally result for the grant round:
     TransactionExecutionError: VM Exception while processing transaction: revert with reason "GrantRound: Incorrect total amount of spent voice credits"
      at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1830:14)
      at HardhatNode.estimateGas (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:693:27)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  9) Grant Round
       claimFunds()
         revert - incorrect amount of spent voice credits:
     TransactionExecutionError: VM Exception while processing transaction: revert with reason "GrantRound: Incorrect total amount of spent voice credits"
      at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1830:14)
      at HardhatNode.estimateGas (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:693:27)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  10) Grant Round Factory
       deployGrantRound()
         allow owner to deploy a grant round:
     Error: VM Exception while processing transaction: reverted with reason string 'Mock on the method is not initialized'
      at <UnrecognizedContract>.<unknown> (0xab302332a07a5cd5d78ebda27f5b3b7c9ac52810)
      at GrantRoundFactory.deployGrantRound (contracts/GrantRoundFactory.sol:156)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  11) Poll - New QV Voting Round
       Create a new Poll
         verify - deploys a new poll correctly:

      AssertionError: expected '0x194Ff9b983D5b899Aa037Bef873B0C96C84…' to equal '0xB550ae8163A275BD1a43D2074716FC384c6…'
      + expected - actual

      -0x194Ff9b983D5b899Aa037Bef873B0C96C843A345
      +0xB550ae8163A275BD1a43D2074716FC384c696265

      at assertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:58:54)
      at tryAssertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:65:20)
      at /Users/daehyun/workspace/qfi/packages/contracts/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:77:13
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)
      at async Context.<anonymous> (tests/QF/02-grantRound.ts:513:7)

  12) Process - Tally QV poll votes
       Verify ZK Proof on chain
         TODO FIX - sbCommitment SHOULD BE correct on poll:

      AssertionError: Expected "19799531091733370011273173049192798918863284564003934970263246829327903710460" to be equal 7043479106494570113902727296596487016802598388511632886880340142095697284066
      + expected - actual

       {
      -  "_hex": "0x0f9277c83d901955f960cd3f920e138c792753e4ddf1e8341fa3fa8c88b18be2"
      +  "_hex": "0x2bc623310fd4e93317e5968defc93ced1c9934f1448c8dc6217a7d12e9d55cfc"
         "_isBigNumber": true
       }

      at Context.<anonymous> (tests/QF/06-finalize.ts:631:45)

  13) Process - Tally QV poll votes
       Verify ZK Proof on chain
         TODO FIX - poll SHOULD verify total spent voice credits:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (tests/QF/06-finalize.ts:657:15)

  14) Process - Tally QV poll votes
       Verify ZK Proof on chain
         TODO FIX - poll SHOULD verifyTallyResult:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (tests/QF/06-finalize.ts:725:14)

  15) Process - Tally QV poll votes
       Verify ZK Proof on chain
         TODO FIX - poll contract SHOULD verifyPerVOSpentVoiceCredits:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (tests/QF/06-finalize.ts:749:15)

  16) Poll - New QV Voting Round
       Create a new Poll
         verify - deploys a new poll correctly:

      AssertionError: expected '0xF4f784Dd8d7eFc4Dc8ACa5402aBef3ECd2b…' to equal '0xB550ae8163A275BD1a43D2074716FC384c6…'
      + expected - actual

      -0xF4f784Dd8d7eFc4Dc8ACa5402aBef3ECd2b5F1D8
      +0xB550ae8163A275BD1a43D2074716FC384c696265

      at assertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:58:54)
      at tryAssertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:65:20)
      at /Users/daehyun/workspace/qfi/packages/contracts/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:77:13
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)
      at async Context.<anonymous> (tests/QV/02-poll.ts:513:7)

  17) Process - Tally QV poll votes
       Verify ZK Proof on chain
         TODO FIX - sbCommitment SHOULD BE correct on poll:

      AssertionError: Expected "21298378014128789371817483863952451625920846377254074999880649946657694127083" to be equal 12546138453081653367553918853068189842014067360462610289429757571660692297365
      + expected - actual

       {
      -  "_hex": "0x1bbcdcdb2ceb3bf8d6b09307be09a7f989b9fba8d0b8cd81031defe586ab9695"
      +  "_hex": "0x2f16746b4bf601f88bbc37191a9192f0a9f37d80cc98d28b7c3469e4caef93eb"
         "_isBigNumber": true
       }

      at Context.<anonymous> (tests/QV/06-verify.ts:631:45)

  18) Process - Tally QV poll votes
       Verify ZK Proof on chain
         TODO FIX - poll SHOULD verify total spent voice credits:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (tests/QV/06-verify.ts:657:15)

  19) Process - Tally QV poll votes
       Verify ZK Proof on chain
         TODO FIX - poll SHOULD verifyTallyResult:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (tests/QV/06-verify.ts:725:14)

  20) Process - Tally QV poll votes
       Verify ZK Proof on chain
         verify - poll contract can verifyPerVOSpentVoiceCredits:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (tests/QV/06-verify.ts:749:15)
```
[full logs](https://gist.github.com/gurrpi/c557d97bb171163ce1b88653051bf84a)

### reproduce procedure
```
cd packages/contracts
yarn run build
yarn run test
```

### misc
it took 30m to test using iMac(3.4GHz iQuad-Core i5)

**Comment by daodesigner** [comment]
will stub out for now since bbug is upstream please keep an eye on: 
https://github.com/appliedzkp/maci/issues/364
https://github.com/appliedzkp/maci/issues/365
https://github.com/appliedzkp/maci/issues/363

https://github.com/appliedzkp/maci/pull/375
