### ISSUE TITLE
Failed to compile subgraph

### ISSUE THREAD

**Issue by gurrpi** [quadratic-funding/qfi#64]
```
yarn run v1.22.17
$ graph build
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping apiVersion from 0.0.4 to 0.0.5
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  Compile data source: QFI => build/QFI/QFI.wasm
⠋ Compile subgraphERROR TS2322: Type '~lib/string/String | null' is not assignable to type '~lib/string/String'.

             const grantRound = GrantRound.load(qfi.currentGrantRound)
                                                ~~~~~~~~~~~~~~~~~~~~~
 in src/QFIMapping.ts(195,48)

ERROR TS2322: Type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt' is not assignable to type 'i32'.

                 BigInt.fromI32(event.params._amount)
                                ~~~~~~~~~~~~~~~~~~~~
 in src/QFIMapping.ts(287,32)

ERROR TS2322: Type 'i32' is not assignable to type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt'.

         grantRound.messageTreeDepth = event.params._treeDepths.messageTreeDepth
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/QFIMapping.ts(369,39)

ERROR TS2322: Type 'i32' is not assignable to type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt'.

         grantRound.messageTreeSubDepth = event.params._treeDepths.messageTreeSubDepth
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/QFIMapping.ts(370,42)

ERROR TS2322: Type 'i32' is not assignable to type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt'.

         grantRound.voteOptionTreeDepth = event.params._treeDepths.voteOptionTreeDepth
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/QFIMapping.ts(371,42)

ERROR TS2322: Type 'i32' is not assignable to type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt'.

         grantRound.intStateTreeDepth = event.params._treeDepths.intStateTreeDepth
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/QFIMapping.ts(372,40)

ERROR TS2322: Type 'i32' is not assignable to type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt'.

         grantRound.messageBatchSize = event.params._batchSizes.messageBatchSize
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/QFIMapping.ts(374,39)

ERROR TS2322: Type 'i32' is not assignable to type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt'.

         grantRound.tallyBatchSize = event.params._batchSizes.tallyBatchSize
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/QFIMapping.ts(375,37)

ERROR TS2322: Type 'i32' is not assignable to type '~lib/string/String'.

         qfi.currentStage = event.params._currentStage
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/QFIMapping.ts(488,28)

ERROR TS2322: Type 'i32' is not assignable to type '~lib/string/String'.

         qfi.currentStage = event.params._currentStage
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/QFIMapping.ts(509,28)

✖ Failed to compile subgraph: Failed to compile data source mapping: 10 compile error(s)
Error: Failed to compile data source mapping: 10 compile error(s)
    at Compiler._compileDataSourceMapping (/Users/daehyun/workspace/qfi/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:307:13)
    at /Users/daehyun/workspace/qfi/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:216:20
    at updateInDeepMap (/Users/daehyun/workspace/qfi/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/Users/daehyun/workspace/qfi/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/Users/daehyun/workspace/qfi/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/Users/daehyun/workspace/qfi/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1278:26)
    at /Users/daehyun/workspace/qfi/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:215:24
    at /Users/daehyun/workspace/qfi/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/Users/daehyun/workspace/qfi/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Users/daehyun/workspace/qfi/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:3015:23)
UNCAUGHT EXCEPTION: Error: The AssemblyScript compiler crashed when compiling this file: 'src/QFIMapping.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.
Also, please contact us so we can make the CLI better by handling errors like this. You can reach out in any of these links:
- Discord channel: https://discord.gg/eM8CA6WA9r
- Github issues: https://github.com/graphprotocol/graph-cli/issues
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

version: https://github.com/quadratic-funding/qfi/commit/d39ced35ce50afdcfa297dcdb3ca5f9cef160a84 (current HEAD of main branch)

## Reproduce procedure
```
cd packages/subgraph
yarn install
yarn codegen
yarn build
```

**Comment by Jeeiii** [comment]
Should be solved in #91
