### ISSUE TITLE
Flaky unit test

### ISSUE THREAD

**Issue by gurrpi** [quadratic-funding/qfi#85]
### Symptom

Test case `revert - max number of messages reached` sometime fails with `TransactionExecutionError: VM Exception while processing transaction: revert with reason "PollE03"` error.

```
2022-04-06T14:20:02.5315172Z   128 passing (2m)
2022-04-06T14:20:02.5315704Z   10 pending
2022-04-06T14:20:02.5315993Z   1 failing
2022-04-06T14:20:02.5316187Z 
2022-04-06T14:20:02.5316434Z   1) Grant Round
2022-04-06T14:20:02.5316827Z        publishMessageBatch()
2022-04-06T14:20:02.5317362Z          revert - max number of messages reached:
2022-04-06T14:20:02.5317979Z      TransactionExecutionError: VM Exception while processing transaction: revert with reason "PollE03"
2022-04-06T14:20:02.5319287Z       at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1952:14)
2022-04-06T14:20:02.5340274Z       at HardhatNode.estimateGas (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:773:27)
2022-04-06T14:20:02.5341321Z       at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
2022-04-06T14:20:02.5342478Z       at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
2022-04-06T14:20:02.5343500Z       at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
2022-04-06T14:20:02.5344609Z Failed to generate 17 stack traces. Run Hardhat with --verbose to learn more.
2022-04-06T14:20:02.5388844Z 
2022-04-06T14:20:02.5388857Z 
2022-04-06T14:20:02.5388866Z 
2022-04-06T14:20:02.6328057Z error Command failed with exit code 1.
2022-04-06T14:20:02.6329638Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-04-06T14:20:02.6590432Z error Command failed with exit code 1.
2022-04-06T14:20:02.6592196Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-04-06T14:20:02.6815033Z error Command failed.
2022-04-06T14:20:02.6815873Z Exit code: 1
```

[full logs](https://github.com/quadratic-funding/qfi/runs/5853249496?check_suite_focus=true)

### Reproduction Procedure

```
yarn install --frozen-lockfile
yarn workspace @quadratic-funding/contracts run generate:abi
yarn workspace @quadratic-funding/contracts run test:unit
```

#### Environment

commit: https://github.com/quadratic-funding/qfi/commit/72c2307f57495cade8074a39e396266a61fa53bf
OS: Ubuntu 20.04
Node: 16
GitHub Action runner: https://github.com/actions/virtual-environments/blob/ubuntu20/20220330.0/images/linux/Ubuntu2004-Readme.md

**Comment by gurrpi** [comment]
@Jeeiii Closing this issue since its fixed by https://github.com/quadratic-funding/qfi/pull/88/commits/7acd88e89d8480a53e13215e58fc88345f002a5f. Thanks @ChallaHalla !
